/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EaApQ8DEQH5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
// import { Label } from "@/components/ui/label"
// import { Input } from "@/components/ui/input"
// import { Textarea } from "@/components/ui/textarea"
import Footer from "./footer"

export function Inicial() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary px-4 lg:px-6 py-4 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6 text-primary-foreground" />
          <span className="text-lg font-semibold text-primary-foreground">Chalé Aconchego</span>
        </Link>
        <nav className="hidden md:flex gap-4">
          <Link href="#" className="text-primary-foreground hover:underline underline-offset-4" prefetch={false}>
            Contato
          </Link>
        </nav>
        <Button variant="outline" className="md:hidden">
          <MenuIcon className="h-6 w-6 text-primary-foreground" />
        </Button>
      </header>
      <main className="flex-1">
        <section className="bg-[url('/assets/banner.jpg')] bg-cover bg-center h-[60vh] relative">
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
            <div className="text-center text-white max-w-xl px-4">
              <h1 className="text-4xl font-bold mb-4">Bem-vindo ao Chalé Aconchego</h1>
              <p className="text-lg mb-8">
                Onde cada detalhe é sinônimo de conforto e tranquilidade em conexão com a natureza!
              </p>
              <Button className="px-6 py-3">Reserve Agora</Button>
            </div>
          </div>
        </section>
        <section className="bg-background py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6 lg:px-8">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <img
                  src="/assets/chale-frente.jpg"
                  width={600}
                  height={400}
                  alt="Chalé Aconchego"
                  className="rounded-lg"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
              <div>
                <h2 className="text-3xl font-bold mb-4">Sobre o Chalé</h2>
                <p className="text-muted-foreground mb-6">
                  Situado na Linha Macaco Branco, em Descanso - SC, o Chalé Aconchego é a fuga perfeita para casais em busca de serenidade.
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="w-5 h-5 text-primary" />
                    <span>Até 2 pessoas</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <BedIcon className="w-5 h-5 text-primary" />
                    <span>1 quarto</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <WifiIcon className="w-5 h-5 text-primary" />
                    <span>Wi-Fi grátis</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ForkKnifeIcon className="w-5 h-5 text-primary" />
                    <span>R$ 300 / noite</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20">
          <div className="px-4 md:px-6 lg:px-8 grid flex justify-center w-100">
            <h2 className="text-3xl font-bold mb-8 text-center">Explore o Chalé</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="rounded-lg overflow-hidden">
                <img
                  src="/assets/chale-frente.jpg"
                  max-width={600}
                  height={400}
                  alt="Sala de estar"
                  className="w-full h-64 object-cover"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-xl font-bold mb-2">Sala de Estar</h3>
                  <p className="text-muted-foreground">
                    Aconchegante sala de estar com lareira e vista para as montanhas.
                  </p>
                </div>
              </div>
              <div className="rounded-lg overflow-hidden">
                <img
                  src="/assets/chale-frente.jpg"
                  max-width={600}
                  height={400}
                  alt="Cozinha"
                  className="w-full h-64 object-cover"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-xl font-bold mb-2">Cozinha</h3>
                  <p className="text-muted-foreground">
                    Cozinha totalmente equipada com tudo o que você precisa para preparar suas refeições.
                  </p>
                </div>
              </div>
              <div className="rounded-lg overflow-hidden">
                <img
                  src="/assets/chale-frente.jpg"
                  max-width={600}
                  height={400}
                  alt="Quarto"
                  className="w-full h-64 object-cover"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-xl font-bold mb-2">Quartos</h3>
                  <p className="text-muted-foreground">Três quartos confortáveis com vista para as montanhas.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-background py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6 lg:px-8">
            <h2 className="text-3xl font-bold mb-8 text-center">Perguntas Frequentes</h2>
            <div className="grid gap-6">
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 rounded-md [&[data-state=open]>svg]:rotate-180">
                  <h3 className="text-lg font-semibold">Quais são as acomodações?</h3>
                  <ChevronDownIcon className="w-5 h-5 text-muted-foreground transition-transform" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-muted px-4 py-3 rounded-b-md">
                  <p className="text-muted-foreground">
                    O chalé possui 1 quarto, 1 banheiro, sala de estar, cozinha totalmente equipada e varanda com vista
                    para as montanhas.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 rounded-md [&[data-state=open]>svg]:rotate-180">
                  <h3 className="text-lg font-semibold">Quais são os serviços incluídos?</h3>
                  <ChevronDownIcon className="w-5 h-5 text-muted-foreground transition-transform" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-muted px-4 py-3 rounded-b-md">
                  <p className="text-muted-foreground">
                    O aluguel inclui Wi-Fi, utensílios de cozinha, roupa de cama e banho, além de limpeza diária.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between bg-muted px-4 py-3 rounded-md [&[data-state=open]>svg]:rotate-180">
                  <h3 className="text-lg font-semibold">Posso levar meu animal de estimação?</h3>
                  <ChevronDownIcon className="w-5 h-5 text-muted-foreground transition-transform" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-muted px-4 py-3 rounded-b-md">
                  <p className="text-muted-foreground">
                    Sim, animais de estimação são bem-vindos no chalé. Apenas solicitamos que você informe sobre a
                    presença do seu pet no momento da reserva.
                  </p>
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </section>
        <section className="bg-muted">
          <Footer />
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6">
        <div className="container px-4 md:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">&copy; 2024 Chalé Aconchego. Todos os direitos reservados.</p>
          <nav className="flex gap-4 mt-4 md:mt-0">
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Política de Privacidade
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Termos de Uso
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function BedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 4v16" />
      <path d="M2 8h18a2 2 0 0 1 2 2v10" />
      <path d="M2 17h20" />
      <path d="M6 8v9" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}

function ForkKnifeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 2L4 20M10 2L10 11M10 22L10 17M14 2L20 8M14 8L20 2" />
    </svg>
  )
}


function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    // <svg
    //   {...props}
    //   xmlns="http://www.w3.org/2000/svg"
    //   width="24"
    //   height="24"
    //   viewBox="0 0 24 24"
    //   fill="none"
    //   stroke="currentColor"
    //   strokeWidth="2"
    //   strokeLinecap="round"
    //   strokeLinejoin="round"
    // >
    //   <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    // </svg>
    <img
      {...props}
      src="assets/logo-chale.png"
      alt="Mountain Icon"
      width="24"
      height="24"
    />
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function WifiIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20h.01" />
      <path d="M2 8.82a15 15 0 0 1 20 0" />
      <path d="M5 12.859a10 10 0 0 1 14 0" />
      <path d="M8.5 16.429a5 5 0 0 1 7 0" />
    </svg>
  )
}
