/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EaApQ8DEQH5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Footer from "./footer"
import Perguntas from "./perguntas"
import Informacoes from "./informacoes"
import { WHATSAPP_LINK } from "@/lib/constants"

export function Inicial() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary px-4 lg:px-6 py-4 flex items-center justify-between h-100">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6 text-primary-foreground" />
          <span className="text-lg font-semibold text-primary-foreground">Chalé Aconchego</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="bg-[url('/assets/banner.jpg')] bg-cover bg-center h-[60vh] relative">
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
            <div className="p-6 rounded-lg shadow-lg max-w-2xl" style={{ backgroundColor: 'rgba(255, 255, 255, 0.8)', position: 'relative' }}>
              <h1 className="text-4xl font-bold text-black text-center mb-2" style={{ position: 'relative', zIndex: 1 }}>
                Bem-vindo ao Chalé Aconchego
              </h1>
              <p className="text-lg text-black text-center" style={{ position: 'relative', zIndex: 1 }}>
                Onde cada detalhe é sinônimo de conforto e tranquilidade em conexão com a natureza!
              </p>
              <div className="flex justify-center pt-5">
                <a
                  href={WHATSAPP_LINK}
                  target="_blank"
                  style={{ position: 'relative', zIndex: 1, color: "white" }}
                  className=" hover:scale-110 bg-[hsl(220.9,39.3%,11%)] inline-block px-6 py-3 bg-blue-500 text-white font-semibold rounded-lg shadow-md hover:bg-blue-600 transition duration-300"
                >
                  Reserve Agora
                </a>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-background py-12 md:py-16 lg:py-20  lg:px-[13%]">
          <div className="container px-4 md:px-6 lg:px-8">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <img
                  src="/assets/chale-frente.jpg"
                  width={600}
                  height={400}
                  alt="Chalé Aconchego"
                  className="rounded-lg"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
              <div>
                <h2 className="text-3xl font-bold mb-4">Sobre o Chalé</h2>
                <p className="text-muted-foreground mb-6">
                  Situado na Linha Macaco Branco, em Descanso - SC, o Chalé Aconchego é a fuga perfeita para casais em busca de serenidade.
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    <UsersIcon className="w-5 h-5 text-primary" />
                    <span>Até 2 pessoas</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CoolIcon className="w-5 h-5 text-primary" />
                    <span>Ar-condicionado</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <WifiIcon className="w-5 h-5 text-primary" />
                    <span>Wi-Fi grátis</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <PetIcon className="w-5 h-5 text-primary" />
                    <span>Pet friendly</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20 lg:px-[15%]">
          <Informacoes />
        </section>
        <section className="bg-background py-12 md:py-16 lg:py-20 lg:px-[15%]">
          <Perguntas />
        </section>
        <section className="bg-muted">
          <Footer />
        </section>
      </main>
    </div>
  )
}

function CoolIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="2" y="3" width="20" height="12" rx="2" />
      <path d="M2 7h20" />
      <path d="M6 15v3" />
      <path d="M12 15v3" />
      <path d="M18 15v3" />
      <path d="M4 19h16" />
    </svg>
  )
}

function PetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
      <path d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75z" />
      <path d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
    </svg>
  )
}

function MountainIcon(props) {
  return (
    <img
      {...props}
      src="assets/logo-chale.png"
      alt="Mountain Icon"
      width="24"
      height="24"
    />
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function WifiIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20h.01" />
      <path d="M2 8.82a15 15 0 0 1 20 0" />
      <path d="M5 12.859a10 10 0 0 1 14 0" />
      <path d="M8.5 16.429a5 5 0 0 1 7 0" />
    </svg>
  )
}
